Update test tool to use dev firebase project
True-Global/prompt-testing pull request #1
Opened 2023-06-02 04:00 UTC by aliabbasmalik8

[Ticket](https://app.clickup.com/t/866aczb5r)

All apis of test tool updated to dev firebase project

2023-06-05 11:06 UTC, emmaalecrim requested changes
Refactor the appConfig into a more standard config file, with options both for dev and prod and defaults/enviroment overrides.

2023-06-07 06:29 UTC, aliabbasmalik8 reviewed
Resolved

2023-06-07 06:31 UTC, aliabbasmalik8 commented
> 

Feedback resolved

2023-06-07 23:05 UTC, emmaalecrim approved these changes

2023-06-07 23:14 UTC, merged